frontend/models/Material.php
<?php

namespace frontend\models;

use frontend\models\enums\MaterialTypes;

/**
 * This is the model class for table "material".
 *
 * @property int $id
 * @property int $type_id
 * @property int $category_id
 * @property string $name
 * @property string|null $authors
 * @property string|null $description

 * @property string $type
 * @property Category $category
 * @property Tag[] $tags
 * @property Link[] $links
 */
class Material extends \yii\db\ActiveRecord
{
    public static function create(
        int $type_id,
        int $category_id,
        string $name,
        $authors = null,
        string $description = null
    ) {
        $material = new static();
        $material->type_id = $type_id;
        $material->category_id = $category_id;
        $material->name = $name;
        $material->authors = $authors ?: null;
        $material->description = $description ?: null;
        return $material;
    }
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'material';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type_id' => 'Type ID',
            'category_id' => 'Category ID',
            'authors' => 'Authors',
            'description' => 'Description',
        ];
    }
    
    public function updateSelf(
        int $type_id,
        int $category_id,
        string $name, $authors = null,
        string $description = null
    ) {
        $this->type_id = $type_id;
        $this->category_id = $category_id;
        $this->name = $name;
        $this->authors = $authors;
        $this->description = $description;
        return $this;
    }
    
    /**
     * @return Tag[]
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])->viaTable('tagToMaterial', ['material_id' => 'id'])->all();
    }
    
    /**
     * @return Link[]
     */
    public function getLinks()
    {
        return $this->hasMany(Link::class, ['material_id' => 'id'])->all();
    }
    
    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id'])->one();
    }
    
    /**
     * @return string
     */
    public function getType()
    {
        return MaterialTypes::getLabel($this->type_id);
    }
}

frontend/controllers/MaterialController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use RuntimeException;
use frontend\readModels\MaterialReadRepository;
use frontend\readModels\TagReadRepository;
use frontend\readModels\LinkReadRepository;
use frontend\readModels\CategoryReadRepository;
use frontend\useCases\material\MaterialService;
use frontend\models\forms\MaterialForm;
use frontend\models\forms\TagForm;
use frontend\models\forms\LinkForm;
use frontend\models\forms\SearchForm;
use frontend\models\enums\MaterialTypes;

/**
 * Description of MaterialController
 *
 * @author kjyra
 */
class MaterialController extends Controller
{
    private $materials;
    private $tags;
    private $links;
    private $categories;
    private $handler;
    
    public function __construct(
            $id, 
            $module, 
            MaterialReadRepository $materials, 
            TagReadRepository $tags, 
            LinkReadRepository $links, 
            CategoryReadRepository $categories, 
            MaterialService $handler, 
            $config = []
        )
    {
        parent::__construct($id, $module, $config);
        $this->materials = $materials;
        $this->tags = $tags;
        $this->links = $links;
        $this->categories = $categories;
        $this->handler = $handler;
    }
    
    public function actionIndex()
    {
        $searchForm = new SearchForm();
        
        if(Yii::$app->request->post())
        {
            $searchForm->load(Yii::$app->request->post());      
        }
        
        $materials = $this->materials->all($searchForm->keyword); 
        
        return $this->render('index', [
            'materials' => $materials,
            'searchForm' => $searchForm,
        ]);
    }
    
    public function actionView(int $id)
    {
        $material = $this->materials->get($id);
        $tagForm = new TagForm();
        $tags = $this->tags->findNotInMaterial($material);
            if($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
                try {
                    $this->handler->addTag($tagForm, $material);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (RuntimeException $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
       
       return $this->render('view', [
           'material' => $material,
           'tags' => $tags,
           'tagForm' => $tagForm,
       ]); 
    }
    
    public function actionCreate()
    {
       $materialForm = new MaterialForm();
       $types = MaterialTypes::listData();
       $categories = $this->categories->all();
       if($materialForm->load(Yii::$app->request->post()) && $materialForm->validate()) {
           try {
               $this->handler->handleCreate($materialForm);
               Yii::$app->session->setFlash('success', 'Материал успешно создан');
               return $this->redirect(['/material']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       
       return $this->render('create', [
           'materialForm' => $materialForm,
           'types' => $types,
           'categories' => $categories,
       ]); 
    }
    
    public function actionUpdate(int $id)
    {
       $material = $this->materials->get($id);
       $types = MaterialTypes::listData();
       $categories = $this->categories->all();
       $materialForm = new MaterialForm();
       if($materialForm->load(Yii::$app->request->post()) && $materialForm->validate()) {
           try {
               $this->handler->handleUpdate($materialForm, $material->id);
               Yii::$app->session->setFlash('success', 'Материал успешно обновлен');
               return $this->redirect(['/material']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       
       return $this->render('update', [
           'materialForm' => $materialForm,
           'material' => $material,
           'types' => $types,
           'categories' => $categories,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $material = $this->materials->get($id);
        try {
            $this->handler->deleteMaterial($material);
            Yii::$app->session->setFlash('success', 'Материал успешно удален.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionDeleteTag(int $tagId, int $materialId)
    {
        $tag = $this->tags->get($tagId);
        $material = $this->materials->get($materialId);
        try {
            $this->handler->deleteTag($tag, $material);
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionDeleteLink(int $linkId)
    {
        $link = $this->links->find($linkId);
        try {
            $this->handler->deleteLink($link);
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionLinkModal()
    {
       $material = $this->materials->get(Yii::$app->request->get('id'));
       $linkForm = new LinkForm();
       if($linkForm->load(Yii::$app->request->post())) {
           if($linkForm->validate()) {
                try {
                    $this->handler->handleAddLink($linkForm, $material);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (RutimeException $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                }
           } else {
                Yii::$app->session->setFlash('error', 'Введите ссылку.');
                return $this->redirect(Yii::$app->request->referrer);
           }
       }
       
       return $this->renderPartial('link/link-modal', [
           'linkForm' => $linkForm,
           'material' => $material,
       ]); 
    }
    
    public function actionLinkModalUpdate()
    {
       $link = $this->links->find(Yii::$app->request->get('id'));
       $linkForm = new LinkForm();
       if($linkForm->load(Yii::$app->request->post())) {
           if($linkForm->validate()) {
                try {
                    $this->handler->handleUpdateLink($linkForm, $link->id);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (\Exception $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                }
           } else {
                Yii::$app->session->setFlash('error', 'Введите ссылку.');
                return $this->redirect(Yii::$app->request->referrer);
           }
       }
       return $this->renderPartial('link/link-modal-update', [
           'linkForm' => $linkForm,
           'link' => $link,
       ]);
    }
}

frontend/controllers/TagController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\readModels\TagReadRepository;
use frontend\models\forms\TagForm;
use frontend\useCases\tag\TagService;

/**
 * Description of TagController
 *
 * @author grigo
 */
class TagController extends Controller
{
    private $tags;
    private $handler;

    public function __construct($id, $module, TagReadRepository $tags, TagService $handler, $config = array())
    {
        $this->tags = $tags;
        $this->handler = $handler;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex() {
        $tags = $this->tags->all();
        return $this->render('index', [
            'tags' => $tags
        ]);
    }
    
    public function actionView(int $id) {
        $tag = $this->tags->get($id);
        return $this->render('view', [
            'tag' => $tag
        ]);
    }

    public function actionCreate()
    {
        $tagForm = new TagForm();
        if ($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
            try {
                $this->handler->handleCreate($tagForm);
                Yii::$app->session->setFlash('success', 'Тег успешно создан');
                return $this->redirect(['/tag']);
            } catch (RuntimeException $ex) {
                Yii::$app->session->setFlash('error', $ex->getMessage());
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return $this->render('create', [
            'tagForm' => $tagForm
        ]);
    }

    public function actionUpdate(int $id)
    {
       $tag = $this->tags->get($id);
       $tagForm = new TagForm();
       if($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
           try {
               $this->handler->handleUpdate($tagForm, $tag->id);
               Yii::$app->session->setFlash('success', 'Тег успешно обновлен');
               return $this->redirect(['/tag']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       return $this->render('update', [
           'tagForm' => $tagForm,
           'tag' => $tag,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $tag = $this->tags->get($id);
        try {
            $this->handler->handleDelete($tag);
            Yii::$app->session->setFlash('success', 'Тег успешно удален.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/views/material/create.php
<?php

/* @var $categories frontend\models\Category[] */
/* @var $types array */
/* @var $materialForm frontend\models\forms\MaterialForm */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Добавить материал</h1>
    <div class="row">
        <div class="col-lg-5 col-md-8">
            <?php $form = ActiveForm::begin(); ?>
            <?=
            $form->field($materialForm, 'type', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->dropDownList($types, [
                'prompt' => 'Выберите тип',
                'class' => 'form-select input-input',
                'id' => "floatingSelectType",
            ])->label('Тип', [
                'for' => 'floatingSelectType',
                'class' => false
            ]);

            ?>
            <?=
            $form->field($materialForm, 'category', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->dropDownList(ArrayHelper::map($categories, 'id', 'name'), [
                'prompt' => 'Выберите категорию',
                'class' => 'form-select input-input',
                'id' => "floatingSelectCategory",
            ])->label('Категория', [
                'for' => 'floatingSelectCategory',
                'class' => false
            ]);

            ?>
            <?=
            $form->field($materialForm, 'name', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textInput([
                'name',
                'placeholder' => 'Напишите название',
                'id' => 'floatingName'
            ])->label('Название', [
                'for' => 'floatingName',
                'class' => false
            ]);

            ?>
            <?=
            $form->field($materialForm, 'authors', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textInput(['authors', 'placeholder' => 'Напишите авторов', 'id' => 'floatingAuthor'])->label('Авторы', [
                'for' => 'floatingAuthor',
                'class' => false
            ]);

            ?>
            <?=
            $form->field($materialForm, 'desc', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textarea([
                'placeholder' => 'Напишите краткое описание',
                'id' => 'floatingDescription'
            ])->label('Описание', [
                'for' => 'floatingDescription',
                'class' => false
            ]);

            ?>
<?= Html::submitButton('Добавить', ['class' => 'btn btn-primary']); ?>
<?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/material/index.php
<?php

/* @var $materials frontend\models\Material[] */
/* @var $searchForm frontend\models\forms\SearchForm */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Материалы</h1>
    <a class="btn btn-primary mb-4" href="<?= Url::to(['/material/create']); ?>" role="button">Добавить</a>
    <div class="row">
        <div class="col-md-8">
            <?php
            $form = ActiveForm::begin([
                        'fieldConfig' => [
                            'options' => [
                                'tag' => false,
                            ]
                        ]
            ]);
            ?>
            <div class="input-group mb-3">
                <?=
                $form->field($searchForm, 'keyword', [
                    'inputOptions' => ['class' => 'form-control']
                ])->label(false);
                ?>
<?= Html::submitButton('Искать', ['class' => 'btn btn-primary']); ?>
            </div>
<?php ActiveForm::end(); ?>
        </div>
    </div>
    <?php if($materials): ?>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Автор</th>
                    <th scope="col">Тип</th>
                    <th scope="col">Категория</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                    <?php foreach($materials as $material): ?>
                        <tr>
                            <td><a href="<?= Url::to(['material/view', 'id' => $material->id]); ?>"><?= $material->name; ?></a></td>
                            <td><?= $material->authors; ?></td>
                            <td><?= $material->getType(); ?></td>
                            <td><?= $material->getCategory()->name; ?></td>
                            <td class="text-nowrap text-end">
                                <a href="<?= Url::to(['material/update', 'id' => $material->id]); ?>" class="text-decoration-none me-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                    </svg>
                                </a>
                                <a href="<?= Url::to(['material/delete', 'id' => $material->id]); ?>" class="text-decoration-none delete">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd"
                                              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php else: ?>
        <?php if($searchForm->keyword): ?>
            <p>По запросу <b><?= $searchForm->keyword; ?></b> ничего не найдено</p>
        <?php else: ?>
            <p>Материалов нет</p>
        <?php endif; ?>
    <?php endif; ?>
</div>

frontend/views/material/update.php
<?php

/* @var $categories frontend\models\Category[] */
/* @var $material frontend\models\Material */
/* @var $types array */
/* @var $materialForm frontend\models\forms\MaterialForm */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Обновить материал</h1>
    <div class="row">
        <div class="col-lg-5 col-md-8">
    <?php $form = ActiveForm::begin(); ?>
    <?=
    $form->field($materialForm, 'type', ['options' => [
            'class' => 'form-floating mb-3',
]])->dropDownList($types, [
        'prompt' => 'Выберите тип',
        'class' => 'form-select input-input',
        'id' => "floatingSelectType",
        'options' => [
            $material->type_id => ['Selected' => true]
        ]       
    ])->label('Тип', [
        'for' => 'floatingSelectType',
        'class' => false
    ]);
    ?>
    <?=
    $form->field($materialForm, 'category', ['options' => [
            'class' => 'form-floating mb-3',
]])->dropDownList(ArrayHelper::map($categories, 'id', 'name'), [
        'prompt' => 'Выберите категорию',
        'class' => 'form-select input-input',
        'id' => "floatingSelectCategory",
        'options' => [
            $material->category_id => ['Selected' => true]
        ]   
    ])->label('Категория', [
        'for' => 'floatingSelectCategory',
        'class' => false
    ]);
    ?>
    <?=
    $form->field($materialForm, 'name', ['options' => [
            'class' => 'form-floating mb-3',
]])->textInput([
        'name',
        'placeholder' => 'Напишите название',
        'value' => $material->name,
        'id' => 'floatingName'
    ])->label('Название', [
        'for' => 'floatingName',
        'class' => false
    ]);
    ?>
    <?=
    $form->field($materialForm, 'authors', ['options' => [
            'class' => 'form-floating mb-3',
]])->textInput(['authors', 'placeholder' => 'Напишите авторов', 
        'value' => $material->authors,
        'id' => 'floatingAuthor'])->label('Авторы', [
        'for' => 'floatingAuthor',
        'class' => false
    ]);
    ?>
    <?=
    $form->field($materialForm, 'desc', ['options' => [
            'class' => 'form-floating mb-3',
]])->textarea([
        'placeholder' => 'Напишите краткое описание',
        'value' => $material->description,
        'id' => 'floatingDescription'
    ])->label('Описание', [
        'for' => 'floatingDescription',
        'class' => false
    ]);
    ?>
<?= Html::submitButton('Добавить', ['class' => 'btn btn-primary']); ?>
<?php ActiveForm::end(); ?>
</div>
    </div>
</div>

frontend/views/material/view.php
<?php

/* @var $material frontend\models\Material */
/* @var $tags frontend\models\Tag[] */
/* @var $tagForm frontend\models\forms\TagForm */

use yii\helpers\Url;
?>
<div class="container">
            <h1 class="my-md-5 my-4"><?= $material->name; ?></h1>
            <div class="row mb-3">
                <div class="col-lg-6 col-md-8">
                    <div class="d-flex text-break">
                        <p class="col fw-bold mw-25 mw-sm-30 me-2">Авторы</p>
                        <p class="col"><?= $material->authors; ?></p>
                    </div>
                    <div class="d-flex text-break">
                        <p class="col fw-bold mw-25 mw-sm-30 me-2">Тип</p>
                        <p class="col"><?= $material->getType(); ?></p>
                    </div>
                    <div class="d-flex text-break">
                        <p class="col fw-bold mw-25 mw-sm-30 me-2">Категория</p>
                        <p class="col"><?= $material->getCategory()->name; ?></p>
                    </div>
                    <div class="d-flex text-break">
                        <p class="col fw-bold mw-25 mw-sm-30 me-2">Описание</p>
                        <p class="col">
                            <?php if($material->description): ?>
                                <?= $material->description; ?>
                            <?php else: ?>
                                Без описания
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?php $form = yii\widgets\ActiveForm::begin([
                                        'method' => 'post',
                                        'enableAjaxValidation' => false,
                                        'fieldConfig' => [
                                            'options' => [
                                                'tag' => false,
                                            ]
                                        ]
                                    ]); ?>
                        <h3>Теги</h3>
                        <div class="input-group mb-3">
                                        <?= $form->field($tagForm, 'name')->dropDownList(
                     yii\helpers\ArrayHelper::map($tags, 'name', 'name'), 
                                                ['class' => 'form-select', 'id'=>"selectAddTag", 'aria-label'=>"Добавьте автора"]
                                                )->label(''); ?>
                            
                            <?= \yii\helpers\Html::submitButton('Добавить', ['class' => 'btn btn-primary']); ?>
                        </div>
                    <?php yii\widgets\ActiveForm::end(); ?>
                    <ul class="list-group mb-4">
                        <?php foreach($material->getTags() as $tag): ?>
                        <li class="list-group-item list-group-item-action d-flex justify-content-between">
                            <a href="<?= Url::to(['tag/view', 'id' => $tag->id]); ?>" class="me-3">
                                <?= $tag->name ?>
                            </a>
                            <a href="<?= Url::to(['material/delete-tag', 'tagId' => $tag->id, 'materialId' => $material->id]); ?>" class="text-decoration-none delete">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd"
                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="col-md-6 links">
                    <div class="d-flex justify-content-between mb-3">
                        <h3>Ссылки</h3>
                        <a class="btn btn-primary modal-link" data-id="<?= $material->id; ?>" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Добавить</a>
                    </div>
                    <ul class="list-group mb-4">
                        <?php foreach($material->getLinks() as $link): ?>
                            <li class="list-group-item list-group-item-action d-flex justify-content-between">
                                <a href="<?= $link->url; ?>" class="me-3">
                                    <?php if($link->name): ?>
                                        <?= $link->name; ?>
                                    <?php else: ?>
                                        <?= $link->url; ?>
                                    <?php endif; ?>
                                </a>
                                <span class="text-nowrap">
                                <a class="text-decoration-none me-2 modal-link-update" data-id="<?= $link->id; ?>" data-bs-toggle="modal" href="#exampleModalToggle">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>
                                </a>
                            <a href="<?= Url::to(['material/delete-link', 'linkId' => $link->id]); ?>" class="text-decoration-none delete">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd"
                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </a>
                            </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    <div class="modal fade" id="exampleModalToggle" aria-labelledby="exampleModalToggleLabel" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            
        </div>
    </div>
</div>