frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\readModels\CategoryReadRepository;
use frontend\useCases\category\CategoryService;
use frontend\models\forms\CategoryForm;

/**
 * Description of TagController
 *
 * @author grigo
 */
class CategoryController extends Controller
{
    private $categories;
    private $handler;

    public function __construct($id, $module, CategoryReadRepository $categories, CategoryService $handler, $config = array())
    {
        $this->categories = $categories;
        $this->handler = $handler;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex() {
        $categories = $this->categories->all();
        return $this->render('index', [
            'categories' => $categories
        ]);
    }

    public function actionCreate()
    {
        $categoryForm = new CategoryForm();
        if ($categoryForm->load(Yii::$app->request->post()) && $categoryForm->validate()) {
            try {
                $this->handler->handleCreate($categoryForm);
                Yii::$app->session->setFlash('success', 'Категория успешно создана.');
                return $this->redirect(['/category']);
            } catch (RuntimeException $ex) {
                Yii::$app->session->setFlash('error', $ex->getMessage());
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return $this->render('create', [
            'categoryForm' => $categoryForm
        ]);
    }

    public function actionUpdate(int $id)
    {
       $category = $this->categories->get($id);
       $categoryForm = new CategoryForm();
       if($categoryForm->load(Yii::$app->request->post()) && $categoryForm->validate()) {
           try {
               $this->handler->handleUpdate($categoryForm, $category->id);
               Yii::$app->session->setFlash('success', 'Категория успешно обновлена.');
               return $this->redirect(['/category']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       return $this->render('update', [
           'categoryForm' => $categoryForm,
           'category' => $category,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $category = $this->categories->get($id);
        try {
            $this->handler->handleDelete($category);
            Yii::$app->session->setFlash('success', 'Категория успешно удалена.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/controllers/MaterialController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use RuntimeException;
use frontend\readModels\MaterialReadRepository;
use frontend\readModels\TagReadRepository;
use frontend\readModels\LinkReadRepository;
use frontend\readModels\CategoryReadRepository;
use frontend\useCases\material\MaterialService;
use frontend\models\forms\MaterialForm;
use frontend\models\forms\TagForm;
use frontend\models\forms\LinkForm;
use frontend\models\forms\SearchForm;
use frontend\models\enums\MaterialTypes;

/**
 * Description of MaterialController
 *
 * @author kjyra
 */
class MaterialController extends Controller
{
    private $materials;
    private $tags;
    private $links;
    private $categories;
    private $handler;
    
    public function __construct(
            $id, 
            $module, 
            MaterialReadRepository $materials, 
            TagReadRepository $tags, 
            LinkReadRepository $links, 
            CategoryReadRepository $categories, 
            MaterialService $handler, 
            $config = []
        )
    {
        parent::__construct($id, $module, $config);
        $this->materials = $materials;
        $this->tags = $tags;
        $this->links = $links;
        $this->categories = $categories;
        $this->handler = $handler;
    }
    
    public function actionIndex()
    {
        $searchForm = new SearchForm();
        
        if(Yii::$app->request->post())
        {
            $searchForm->load(Yii::$app->request->post());      
        }
        
        $materials = $this->materials->all($searchForm->keyword); 
        
        return $this->render('index', [
            'materials' => $materials,
            'searchForm' => $searchForm,
        ]);
    }
    
    public function actionView(int $id)
    {
        $material = $this->materials->get($id);
        $tagForm = new TagForm();
        $tags = $this->tags->findNotInMaterial($material);
            if($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
                try {
                    $this->handler->addTag($tagForm, $material);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (RuntimeException $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
       
       return $this->render('view', [
           'material' => $material,
           'tags' => $tags,
           'tagForm' => $tagForm,
       ]); 
    }
    
    public function actionCreate()
    {
       $materialForm = new MaterialForm();
       $types = MaterialTypes::listData();
       $categories = $this->categories->all();
       if($materialForm->load(Yii::$app->request->post()) && $materialForm->validate()) {
           try {
               $this->handler->handleCreate($materialForm);
               Yii::$app->session->setFlash('success', 'Материал успешно создан');
               return $this->redirect(['/material']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       
       return $this->render('create', [
           'materialForm' => $materialForm,
           'types' => $types,
           'categories' => $categories,
       ]); 
    }
    
    public function actionUpdate(int $id)
    {
       $material = $this->materials->get($id);
       $types = MaterialTypes::listData();
       $categories = $this->categories->all();
       $materialForm = new MaterialForm();
       if($materialForm->load(Yii::$app->request->post()) && $materialForm->validate()) {
           try {
               $this->handler->handleUpdate($materialForm, $material->id);
               Yii::$app->session->setFlash('success', 'Материал успешно обновлен');
               return $this->redirect(['/material']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       
       return $this->render('update', [
           'materialForm' => $materialForm,
           'material' => $material,
           'types' => $types,
           'categories' => $categories,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $material = $this->materials->get($id);
        try {
            $this->handler->deleteMaterial($material);
            Yii::$app->session->setFlash('success', 'Материал успешно удален.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionDeleteTag(int $tagId, int $materialId)
    {
        $tag = $this->tags->get($tagId);
        $material = $this->materials->get($materialId);
        try {
            $this->handler->deleteTag($tag, $material);
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionDeleteLink(int $linkId)
    {
        $link = $this->links->find($linkId);
        try {
            $this->handler->deleteLink($link);
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionLinkModal()
    {
       $material = $this->materials->get(Yii::$app->request->get('id'));
       $linkForm = new LinkForm();
       if($linkForm->load(Yii::$app->request->post())) {
           if($linkForm->validate()) {
                try {
                    $this->handler->handleAddLink($linkForm, $material);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (RutimeException $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                }
           } else {
                Yii::$app->session->setFlash('error', 'Введите ссылку.');
                return $this->redirect(Yii::$app->request->referrer);
           }
       }
       
       return $this->renderPartial('link/link-modal', [
           'linkForm' => $linkForm,
           'material' => $material,
       ]); 
    }
    
    public function actionLinkModalUpdate()
    {
       $link = $this->links->find(Yii::$app->request->get('id'));
       $linkForm = new LinkForm();
       if($linkForm->load(Yii::$app->request->post())) {
           if($linkForm->validate()) {
                try {
                    $this->handler->handleUpdateLink($linkForm, $link->id);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (\Exception $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                }
           } else {
                Yii::$app->session->setFlash('error', 'Введите ссылку.');
                return $this->redirect(Yii::$app->request->referrer);
           }
       }
       return $this->renderPartial('link/link-modal-update', [
           'linkForm' => $linkForm,
           'link' => $link,
       ]);
    }
}

frontend/controllers/TagController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\readModels\TagReadRepository;
use frontend\models\forms\TagForm;
use frontend\useCases\tag\TagService;

/**
 * Description of TagController
 *
 * @author grigo
 */
class TagController extends Controller
{
    private $tags;
    private $handler;

    public function __construct($id, $module, TagReadRepository $tags, TagService $handler, $config = array())
    {
        $this->tags = $tags;
        $this->handler = $handler;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex() {
        $tags = $this->tags->all();
        return $this->render('index', [
            'tags' => $tags
        ]);
    }
    
    public function actionView(int $id) {
        $tag = $this->tags->get($id);
        return $this->render('view', [
            'tag' => $tag
        ]);
    }

    public function actionCreate()
    {
        $tagForm = new TagForm();
        if ($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
            try {
                $this->handler->handleCreate($tagForm);
                Yii::$app->session->setFlash('success', 'Тег успешно создан');
                return $this->redirect(['/tag']);
            } catch (RuntimeException $ex) {
                Yii::$app->session->setFlash('error', $ex->getMessage());
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return $this->render('create', [
            'tagForm' => $tagForm
        ]);
    }

    public function actionUpdate(int $id)
    {
       $tag = $this->tags->get($id);
       $tagForm = new TagForm();
       if($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
           try {
               $this->handler->handleUpdate($tagForm, $tag->id);
               Yii::$app->session->setFlash('success', 'Тег успешно обновлен');
               return $this->redirect(['/tag']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       return $this->render('update', [
           'tagForm' => $tagForm,
           'tag' => $tag,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $tag = $this->tags->get($id);
        try {
            $this->handler->handleDelete($tag);
            Yii::$app->session->setFlash('success', 'Тег успешно удален.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/views/layouts/library.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use frontend\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="main-wrapper">
    <div class="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="<?= UrL::to(['/site']); ?>">Test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link <?php if(Url::current() === '/material/index'): echo 'active'; endif; ?>" <?php if(Url::current() == '/material/index'): echo 'aria-current="page"'; endif; ?>  href="<?= Url::to(['/material']); ?>">Материалы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?php if(Url::current() === '/tag/index'): echo 'active'; endif; ?>" <?php if(Url::current() == '/tag/index'): echo 'aria-current="page"'; endif; ?> href="<?= Url::to(['/tag']); ?>">Теги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?php if(Url::current() === '/category/index'): echo 'active'; endif; ?>" <?php if(Url::current() == '/category/index'): echo 'aria-current="page"'; endif; ?> href="<?= Url::to(['/category']); ?>">Категории</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
            <?php if( Yii::$app->session->hasFlash('success') ): ?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <?php echo Yii::$app->session->getFlash('success'); ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            <?php endif;?>
            <?php if( Yii::$app->session->hasFlash('error') ): ?>
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <?php echo Yii::$app->session->getFlash('error'); ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            <?php endif;?>
            <?= $content; ?>
    </div>
    <footer class="footer py-4 mt-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col text-muted">Test</div>
            </div>
        </div>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Contact', 'url' => ['/site/contact']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>