frontend/models/Category.php
<?php

namespace frontend\models;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $name

 * @property Material[] $materials
 */
class Category extends \yii\db\ActiveRecord
{
    public static function create(string $name)
    {
        $category = new static();
        $category->name = $name;
        return $category;
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }
    
    public function updateSelf(string $name)
    {
        $this->name = $name;
        return $this;
    }
    
    /**
     * @return Material[]
     */
    public function getMaterials()
    {
        return Material::find()->where(['category_id' => $this->id])->all();
    }
}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\readModels\CategoryReadRepository;
use frontend\useCases\category\CategoryService;
use frontend\models\forms\CategoryForm;

/**
 * Description of TagController
 *
 * @author grigo
 */
class CategoryController extends Controller
{
    private $categories;
    private $handler;

    public function __construct($id, $module, CategoryReadRepository $categories, CategoryService $handler, $config = array())
    {
        $this->categories = $categories;
        $this->handler = $handler;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex() {
        $categories = $this->categories->all();
        return $this->render('index', [
            'categories' => $categories
        ]);
    }

    public function actionCreate()
    {
        $categoryForm = new CategoryForm();
        if ($categoryForm->load(Yii::$app->request->post()) && $categoryForm->validate()) {
            try {
                $this->handler->handleCreate($categoryForm);
                Yii::$app->session->setFlash('success', 'Категория успешно создана.');
                return $this->redirect(['/category']);
            } catch (RuntimeException $ex) {
                Yii::$app->session->setFlash('error', $ex->getMessage());
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return $this->render('create', [
            'categoryForm' => $categoryForm
        ]);
    }

    public function actionUpdate(int $id)
    {
       $category = $this->categories->get($id);
       $categoryForm = new CategoryForm();
       if($categoryForm->load(Yii::$app->request->post()) && $categoryForm->validate()) {
           try {
               $this->handler->handleUpdate($categoryForm, $category->id);
               Yii::$app->session->setFlash('success', 'Категория успешно обновлена.');
               return $this->redirect(['/category']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       return $this->render('update', [
           'categoryForm' => $categoryForm,
           'category' => $category,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $category = $this->categories->get($id);
        try {
            $this->handler->handleDelete($category);
            Yii::$app->session->setFlash('success', 'Категория успешно удалена.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/views/category/create.php
<?php

/* @var $categoryForm frontend\models\forms\CategoryForm */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Добавить категорию</h1>
    <div class="row">
        <div class="col-lg-5 col-md-8">
            <?php $form = ActiveForm::begin(); ?>
            <?=
            $form->field($categoryForm, 'name', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textInput([
                'name',
                'class' => 'form-control',
                'placeholder' => 'Напишите название',
                'id' => 'floatingName',
            ])->label('Название', [
                'for' => 'floatingName',
                'class' => false
            ]);

            ?>
<?= Html::submitButton('Добавить', ['class' => 'btn btn-primary validate']); ?>
<?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/category/index.php
<?php

/* @var $categories frontend\models\Category[] */

use yii\helpers\Url;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Категории</h1>
    <a class="btn btn-primary mb-4" href="<?= Url::to(['/category/create']); ?>" role="button">Добавить</a>
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group mb-4">
                <li class="list-group-item d-flex justify-content-between">
                    <strong>Название</strong>
                </li>
<?php if ($categories): ?>
                            <?php foreach ($categories as $category): ?>
                        <li class="list-group-item list-group-item-action d-flex justify-content-between">
                            <span class="me-3">
        <?= $category->name; ?>
                            </span>
                            <span class="text-nowrap">
                                <a href="<?= Url::to(['/category/update', 'id' => $category->id]); ?>" class="text-decoration-none me-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                    </svg>
                                </a>
                                <a href="<?= Url::to(['/category/delete', 'id' => $category->id]); ?>" class="text-decoration-none delete">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd"
                                              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                    </svg>
                                </a>
                            </span>
                        </li>
    <?php endforeach; ?>
<?php endif; ?>
            </ul>
        </div>
    </div>
</div>

frontend/views/category/update.php
<?php

/* @var $categoryForm frontend\models\forms\CategoryForm */
/* @var $category frontend\models\Category */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<div class="container">
    <h1 class="my-md-5 my-4">обновить категорию</h1>
    <div class="row">
        <div class="col-lg-5 col-md-8">
            <?php $form = ActiveForm::begin(); ?>
            <?=
            $form->field($categoryForm, 'name', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textInput([
                'name',
                'class' => 'form-control',
                'placeholder' => 'Напишите название',
                'value' => $category->name,
                'id' => 'floatingName',
            ])->label('Название', [
                'for' => 'floatingName',
                'class' => false
            ]);

            ?>
<?= Html::submitButton('Добавить', ['class' => 'btn btn-primary validate']); ?>
<?php ActiveForm::end(); ?>
        </div>
    </div>
</div>