frontend/models/Tag.php
<?php

namespace frontend\models;


/**
 * This is the model class for table "tag".
 *
 * @property int $id
 * @property string $name

 * @property Material[] $materials
 */
class Tag extends \yii\db\ActiveRecord
{
    public static function create(string $name)
    {
        $tag = new static();
        $tag->name = $name;
        return $tag;
    }
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tag';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }
    
    public function updateSelf(string $name)
    {
        $this->name = $name;
        return $this;
    }
    
    /**
     * @return Material[]
     */
    public function getMaterials()
    {
        return $this->hasMany(Material::class, ['id' => 'material_id'])->viaTable('tagToMaterial', ['tag_id' => 'id'])->all();
    }
}

frontend/controllers/MaterialController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use RuntimeException;
use frontend\readModels\MaterialReadRepository;
use frontend\readModels\TagReadRepository;
use frontend\readModels\LinkReadRepository;
use frontend\readModels\CategoryReadRepository;
use frontend\useCases\material\MaterialService;
use frontend\models\forms\MaterialForm;
use frontend\models\forms\TagForm;
use frontend\models\forms\LinkForm;
use frontend\models\forms\SearchForm;
use frontend\models\enums\MaterialTypes;

/**
 * Description of MaterialController
 *
 * @author kjyra
 */
class MaterialController extends Controller
{
    private $materials;
    private $tags;
    private $links;
    private $categories;
    private $handler;
    
    public function __construct(
            $id, 
            $module, 
            MaterialReadRepository $materials, 
            TagReadRepository $tags, 
            LinkReadRepository $links, 
            CategoryReadRepository $categories, 
            MaterialService $handler, 
            $config = []
        )
    {
        parent::__construct($id, $module, $config);
        $this->materials = $materials;
        $this->tags = $tags;
        $this->links = $links;
        $this->categories = $categories;
        $this->handler = $handler;
    }
    
    public function actionIndex()
    {
        $searchForm = new SearchForm();
        
        if(Yii::$app->request->post())
        {
            $searchForm->load(Yii::$app->request->post());      
        }
        
        $materials = $this->materials->all($searchForm->keyword); 
        
        return $this->render('index', [
            'materials' => $materials,
            'searchForm' => $searchForm,
        ]);
    }
    
    public function actionView(int $id)
    {
        $material = $this->materials->get($id);
        $tagForm = new TagForm();
        $tags = $this->tags->findNotInMaterial($material);
            if($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
                try {
                    $this->handler->addTag($tagForm, $material);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (RuntimeException $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
       
       return $this->render('view', [
           'material' => $material,
           'tags' => $tags,
           'tagForm' => $tagForm,
       ]); 
    }
    
    public function actionCreate()
    {
       $materialForm = new MaterialForm();
       $types = MaterialTypes::listData();
       $categories = $this->categories->all();
       if($materialForm->load(Yii::$app->request->post()) && $materialForm->validate()) {
           try {
               $this->handler->handleCreate($materialForm);
               Yii::$app->session->setFlash('success', 'Материал успешно создан');
               return $this->redirect(['/material']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       
       return $this->render('create', [
           'materialForm' => $materialForm,
           'types' => $types,
           'categories' => $categories,
       ]); 
    }
    
    public function actionUpdate(int $id)
    {
       $material = $this->materials->get($id);
       $types = MaterialTypes::listData();
       $categories = $this->categories->all();
       $materialForm = new MaterialForm();
       if($materialForm->load(Yii::$app->request->post()) && $materialForm->validate()) {
           try {
               $this->handler->handleUpdate($materialForm, $material->id);
               Yii::$app->session->setFlash('success', 'Материал успешно обновлен');
               return $this->redirect(['/material']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       
       return $this->render('update', [
           'materialForm' => $materialForm,
           'material' => $material,
           'types' => $types,
           'categories' => $categories,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $material = $this->materials->get($id);
        try {
            $this->handler->deleteMaterial($material);
            Yii::$app->session->setFlash('success', 'Материал успешно удален.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionDeleteTag(int $tagId, int $materialId)
    {
        $tag = $this->tags->get($tagId);
        $material = $this->materials->get($materialId);
        try {
            $this->handler->deleteTag($tag, $material);
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionDeleteLink(int $linkId)
    {
        $link = $this->links->find($linkId);
        try {
            $this->handler->deleteLink($link);
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    public function actionLinkModal()
    {
       $material = $this->materials->get(Yii::$app->request->get('id'));
       $linkForm = new LinkForm();
       if($linkForm->load(Yii::$app->request->post())) {
           if($linkForm->validate()) {
                try {
                    $this->handler->handleAddLink($linkForm, $material);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (RutimeException $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                }
           } else {
                Yii::$app->session->setFlash('error', 'Введите ссылку.');
                return $this->redirect(Yii::$app->request->referrer);
           }
       }
       
       return $this->renderPartial('link/link-modal', [
           'linkForm' => $linkForm,
           'material' => $material,
       ]); 
    }
    
    public function actionLinkModalUpdate()
    {
       $link = $this->links->find(Yii::$app->request->get('id'));
       $linkForm = new LinkForm();
       if($linkForm->load(Yii::$app->request->post())) {
           if($linkForm->validate()) {
                try {
                    $this->handler->handleUpdateLink($linkForm, $link->id);
                    return $this->redirect(Yii::$app->request->referrer);
                } catch (\Exception $ex) {
                    Yii::$app->session->setFlash('error', $ex->getMessage());
                }
           } else {
                Yii::$app->session->setFlash('error', 'Введите ссылку.');
                return $this->redirect(Yii::$app->request->referrer);
           }
       }
       return $this->renderPartial('link/link-modal-update', [
           'linkForm' => $linkForm,
           'link' => $link,
       ]);
    }
}

frontend/controllers/TagController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\readModels\TagReadRepository;
use frontend\models\forms\TagForm;
use frontend\useCases\tag\TagService;

/**
 * Description of TagController
 *
 * @author grigo
 */
class TagController extends Controller
{
    private $tags;
    private $handler;

    public function __construct($id, $module, TagReadRepository $tags, TagService $handler, $config = array())
    {
        $this->tags = $tags;
        $this->handler = $handler;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex() {
        $tags = $this->tags->all();
        return $this->render('index', [
            'tags' => $tags
        ]);
    }
    
    public function actionView(int $id) {
        $tag = $this->tags->get($id);
        return $this->render('view', [
            'tag' => $tag
        ]);
    }

    public function actionCreate()
    {
        $tagForm = new TagForm();
        if ($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
            try {
                $this->handler->handleCreate($tagForm);
                Yii::$app->session->setFlash('success', 'Тег успешно создан');
                return $this->redirect(['/tag']);
            } catch (RuntimeException $ex) {
                Yii::$app->session->setFlash('error', $ex->getMessage());
                return $this->redirect(Yii::$app->request->referrer);
            }
        }

        return $this->render('create', [
            'tagForm' => $tagForm
        ]);
    }

    public function actionUpdate(int $id)
    {
       $tag = $this->tags->get($id);
       $tagForm = new TagForm();
       if($tagForm->load(Yii::$app->request->post()) && $tagForm->validate()) {
           try {
               $this->handler->handleUpdate($tagForm, $tag->id);
               Yii::$app->session->setFlash('success', 'Тег успешно обновлен');
               return $this->redirect(['/tag']);
           } catch (\Exception $ex) {
               Yii::$app->session->setFlash('error', $ex->getMessage());
           }
       }
       return $this->render('update', [
           'tagForm' => $tagForm,
           'tag' => $tag,
       ]);
    }
    
    public function actionDelete(int $id)
    {
        $tag = $this->tags->get($id);
        try {
            $this->handler->handleDelete($tag);
            Yii::$app->session->setFlash('success', 'Тег успешно удален.');
        } catch (RuntimeException $ex) {
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/views/tag/create.php
<?php

/* @var $tagForm frontend\models\forms\TagForm */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Добавить тег</h1>
    <div class="row">
        <div class="col-lg-5 col-md-8">
<?php $form = ActiveForm::begin(); ?>
            <?=
            $form->field($tagForm, 'name', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textInput([
                'name',
                'class' => 'form-control',
                'placeholder' => 'Напишите название',
                'id' => 'floatingName',
            ])->label('Название', [
                'for' => 'floatingName',
                'class' => false
            ])

            ?>
            <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary validate']); ?>
<?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/tag/index.php
<?php

/* @var $tags frontend\models\Tag[] */

use yii\helpers\Url;
?>
<div class="container">
    <h1 class="my-md-5 my-4">Теги</h1>
    <a class="btn btn-primary mb-4" href="<?= Url::to(['/tag/create']); ?>" role="button">Добавить</a>
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group mb-4">
                <li class="list-group-item d-flex justify-content-between">
                    <strong>Название</strong>
                </li>
                <?php foreach($tags as $tag): ?>
                <li class="list-group-item list-group-item-action d-flex justify-content-between">
                    <span class="me-3">
                        <?= $tag->name; ?>
                    </span>
                    <span class="text-nowrap">
                        <a href="<?= Url::to(['/tag/update', 'id' => $tag->id]); ?>" class="text-decoration-none me-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>
                        </a>
                        <a href="<?= Url::to(['/tag/delete', 'id' => $tag->id]); ?>" class="text-decoration-none delete">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd"
                                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </a>
                    </span>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

frontend/views/tag/update.php
<?php

/* @var $tagForm frontend\models\forms\TagForm */
/* @var $tag frontend\models\Tag */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<div class="container">
    <h1 class="my-md-5 my-4">обновить тег</h1>
    <div class="row">
        <div class="col-lg-5 col-md-8">
            <?php $form = ActiveForm::begin(); ?>
            <?=
            $form->field($tagForm, 'name', ['options' => [
                    'class' => 'form-floating mb-3',
            ]])->textInput([
                'name',
                'class' => 'form-control',
                'placeholder' => 'Напишите название',
                'value' => $tag->name,
                'id' => 'floatingName',
            ])->label('Название', [
                'for' => 'floatingName',
                'class' => false
            ])

            ?>
            <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary validate']); ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/tag/view.php
<?php

/* @var $tag frontend\models\Tag */

use yii\helpers\Url;
?>
<div class="container">
    <h1 class="my-md-5 my-4"><?= $tag->name; ?></h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Автор</th>
                    <th scope="col">Тип</th>
                    <th scope="col">Категория</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($tag->getMaterials() as $material): ?>
                    <tr>
                        <td><a href="<?= Url::to(['material/view', 'id' => $material->id]); ?>"><?= $material->name; ?></a></td>
                        <td><?= $material->authors; ?></td>
                        <td><?= $material->getType()->name; ?></td>
                        <td><?= $material->getCategory()->name; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>